name: JSHint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get modified files
        id: modified-files
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.js$')"

      - name: Run JSHint on modified files
        run: |
          for file in ${{ steps.modified-files.outputs.files }}; do
            npx jshint "$file" --reporter --verbose
          done
